# Generated by Django 6.0.5 on 2026-05-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='detected_language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='diarization',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='sentiment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
